/*

**README notes***

- Changed tables a lot... sorry
- For simplicity:
	1. since PA has 8 numeric license No. I went with that... technically wrong but whatever
	2. all license plate numbers are 8 character alpha numeric
- Things I used generatedata.com or other sites for:
	1. names
	2. addresses
		- Some of them are P.O. boxes which is unrealistic, but who cares

- When using generators, I put in placeholders first

*/

drop table payment;
drop table parks;
drop table rental;
drop table charges;
drop table vehicle;
drop table location;
drop table customer;

create table customer
(
	id					int GENERATED BY DEFAULT AS IDENTITY,
	license 			varchar(8),	
	name 				varchar(30) not null,
	address 			varchar(40) not null,
	state				char(2) not null,
	primary key 		(license)
);

create table location
(
	loc_ID				int GENERATED BY DEFAULT AS IDENTITY,
	address				varchar(40) not null,
	state				char(2) not null,
	loc_type			varchar(20) not null check (loc_type in ('Airport','Train Station','City Center','Junkyard')),
	inventory			numeric(3,0) not null check (inventory >= 0),
	primary key 		(loc_ID)
);

create table vehicle
(	
	license_plate		varchar(8),
	make				varchar(20) not null,
	model				varchar(20) not null,
	year				varchar(4) not null check (year >= 1948),
	vehicle_type		varchar(10) not null check (vehicle_type in ('SUV','minicar','subcompact','compact','full size','sports car','minivan','truck')),
	baseRate 			numeric(2) not null,
	odometer			numeric(4,1) not null check (odometer >= 0),
	fuel_used			numeric(3,1) check (fuel_used >= 0),
	damage		        char(3), check (damage in ('yes','no')),
	--total_miles			numeric(6,1) not null check (total_miles >= 0),
	primary key 		(license_plate)
);

/*
create table charges
(
	credit_card			varchar(16),
	vehicle_type		varchar(10) check (vehicle_type in ('SUV','minicar','subcompact','compact','full size','sports car','minivan','truck')),
	fuel				number(7,2),
	damage				number(7,2),
	primary key 		(credit_card, vehicle_type, dropoff, insurance, navigation, child_seat, radio, carbon_offset, fuel, damage),
	foreign key 		(credit_card) references customer on delete cascade,
	foreign key 		(vehicle_type) references vehicle on delete cascade
);
*/

create table parks
(
	loc_ID				int,
	license_plate		varchar(8), 
	primary key 		(loc_ID, license_plate),
	foreign key 		(loc_ID) references location on delete cascade,
	foreign key 		(license_plate) references vehicle on delete cascade
);

create table rental
(
	rental_ID			int GENERATED BY DEFAULT AS IDENTITY,
	cust_license		varchar(8) not null,
	veh_license			varchar(8) not null,
	--rent_date			date not null,
	pickup_loc			int not null,
	credit_card 		varchar(16) not null,
	baseRate 			numeric(2) not null,
	length				numeric(3) not null,
	/*
	discount  			numeric(2,2) not null check (discount in (0.00, 0.20, 0.25)),
	business			varchar(30),
	membership			varchar(4) check (membership in ('AAA','AARP')),
	insurance			number(7,2),
	navigation			number(7,2),
	child_seat			number(7,2),
	radio				number(7,2),
	carbon_offset		number(7,2),*/
	primary key 		(rental_ID),
	foreign key 		(cust_license) references customer (license) on delete cascade,
	foreign key 		(veh_license) references vehicle (license_plate) on delete cascade,
	foreign key 		(pickup_loc) references location (loc_ID) on delete cascade
);


/*
create table payment
(
	rental_ID			int GENERATED BY DEFAULT AS IDENTITY,
	name				varchar(30),
	credit_card 		varchar(16),
	amount				number(7,2) check (amount >= 0),
	primary key 		(rental_ID, amount),
	foreign key 		(rental_ID) references rental on delete cascade,
	foreign key 		(name) references customer on delete cascade,
	foreign key 		(credit_card) references customer on delete cascade
);
*/
